version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    platform: linux/x86_64
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  # เพิ่ม logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    platform: linux/x86_64
    volumes:
      - ./logstash-config:/usr/share/logstash/config
    ports:
      - "5045:5044"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  # เพิ่ม redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - elastic

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - redis-data:/db
    networks:
      - elastic
    depends_on:
      - redis
      
    # เพิ่ม beats (ตัวอย่าง: filebeat)
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    platform: linux/x86_64
    user: root
    volumes:
      - ./filebeat-config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      -  ./filebeat-config/redis.yml:/usr/share/filebeat/modules.d/redis.yml
      -  ./filebeat-config/var/lib/beats:/var/lib/beats
    ports:
      - "5046:5044"
    networks:
      - elastic
    depends_on:
      - logstash

networks:
  elastic:
   driver: bridge
    

volumes:
  elasticsearch-data:
  # เพิ่ม volumes สำหรับ logstash, redis, และ beats
  redis-data:
  redisinsight:

